In [6]:
# 
# In this notebook, you learn:
#
# 1) How to use autograd with tensors without using any Neural Networks?
#

In [1]:
import torch

In [7]:
# By passing the argument 'requires_grad=True', we are telling pytorch that
# t1 is a learnable parameter.
# Every tensor has a 'grad_fn' variable that references the function that created
# the tensor except for the tensors created by the user (These tensors have
# 'grad_fn' set to None).
# t1 and t2 are user created tensors and hence have 'grad_fn' set to None.
# t1 is also a leaf tensor (paramater tensor directly created by the user and 
# not an intermediate tensor created during the gradient calculation).
# Gradients for the leaf tensors are saved in the '.grad' attribute.
t1 = torch.tensor(data=[1, 2], dtype=torch.float, requires_grad=True)
print(t1.shape)
print(t1)
print(t1.grad)

torch.Size([2])
tensor([1., 2.], requires_grad=True)
None


In [8]:
t2 = torch.tensor(data=[-3, -4], dtype=torch.float, requires_grad=True)
print(t2.shape)
print(t2)
print(t2.grad)

torch.Size([2])
tensor([-3., -4.], requires_grad=True)
None


In [9]:
# t3 is created by the addition operation and hence grad_fn is set
# to the appropriate Function object (AddBackward in this case).

t3 = t1 + t2
print(t3.shape)
print(t3)

torch.Size([2])
tensor([-2., -2.], grad_fn=<AddBackward0>)


In [10]:
# This was inferred as element wise multiplication by pytorch.
# Notice the 'grad_fn' object here set to MulBackward appropriately.

t4 = t1 * t2
print(t4.shape)
print(t4)

torch.Size([2])
tensor([-3., -8.], grad_fn=<MulBackward0>)


In [11]:
# Notice that 'grad_fn' here only shows the last operation (meaning Function object 
# corresponding to that last operation) that was part of creating the new tensor 't5' 
# even though it contains multiple tensors (t3, t4) that were created with different 
# operations and have 'grad_fn' set on those tensors.

t5 = t3 - t4
print(t5.shape)
print(t5)

torch.Size([2])
tensor([1., 6.], grad_fn=<SubBackward0>)


In [12]:
# Q = 3(a^3) - (b^2) --> tensor of shape 2 [q1, q2] = t6 below.
# Loss = (q1 + q2) --> We use this as our loss to calculate the
# gradients (t7 below).
# We can also use Q as our Loss function and calculate the gradients. However,
# Q is a tensor and we explicitly need to pass (info) whether we need to
# calculate the derivatives based on every element in Q or only certain elements
# which is cumbersome and not used in ML widely.

t6 = 3*(t1**3) - (t2**2)
print(t6.shape)
print(t6)

torch.Size([2])
tensor([-6.,  8.], grad_fn=<SubBackward0>)


In [13]:
# Loss = (q1 + q2) --> We use this as our loss to calculate the
# gradients (t6). It's a scalar value.

Loss = t6.sum()
print(Loss.shape)
print(Loss)

torch.Size([])
tensor(2., grad_fn=<SumBackward0>)


In [14]:
# Triggering the back propogation calculates the gradients and saves them
# in the grad attribute.

Loss.backward()
print("Printing t1: ")
print(t1)
print(t1.grad)
print("Printing t2: ")
print(t2)
print(t2.grad)

Printing t1: 
tensor([1., 2.], requires_grad=True)
tensor([ 9., 36.])
Printing t2: 
tensor([-3., -4.], requires_grad=True)
tensor([6., 8.])
