In [1]:
# In this notebook, you learn:
#
# What tensor.mean() does?
# What tensor.topk() does?

In [2]:
import torch

## [torch.tensor.mean](https://pytorch.org/docs/stable/generated/torch.mean.html#torch.mean)

In [2]:
# Lets forget about 'keepdim' parameter for now.
# In general, the mean reduces the dimension of the original tensor by 1.
# If you calculate the mean along the dimension 'd', then that dimension ('d') is collapsed in the result.
# The 'keepdim' parameter is just to maintain the original tensor shape for the same mean calculation.
# In general, if the mean is being calculated along dimension 'd', you traverse 'd' levels into the tensor
# to obtain groups of tensors (or numbers) along dimension 'd'. We then collapse each group by calculating 
# the means for each group.

In [5]:
t1 = torch.tensor(data=[1, 2, 3, 4], dtype=torch.float)
print(t1, t1.shape)

tensor([1., 2., 3., 4.]) torch.Size([4])


In [6]:
# (1 + 2 + 3 + 4) / 4 = 2.5
t2 = t1.mean(dim=0, keepdim=True)
print(t2, t2.shape)

tensor([2.5000]) torch.Size([1])


In [7]:
t3 = torch.tensor(data=[[1, 2, 3], [4, 5, 6]], dtype=torch.float)
print(t3, t3.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.Size([2, 3])


In [8]:
# (1 + 4) / 2 = 2.5 --> column 0
# (2 + 5) / 2 = 3.5 --> column 1
# (3 + 6) / 2 = 4.5 --> column 2
t4 = t3.mean(dim=0, keepdim=True)
print(t4, t4.shape)

tensor([[2.5000, 3.5000, 4.5000]]) torch.Size([1, 3])


In [9]:
# (1 + 2 + 3) / 3 = 2 --> row 0
# (4 + 5 + 6) / 3 = 5 --> row 1
t5 = t3.mean(dim=1, keepdim=True)
print(t5, t5.shape)

tensor([[2.],
        [5.]]) torch.Size([2, 1])


In [10]:
# Calculates the mean of all the elements in the tensor.
# (1 + 2 + 3 + 4 + 5 + 6) / 6 = 3.5
t5_5 = t3.mean()
print(t5_5, t5_5.shape)

tensor(3.5000) torch.Size([])


In [11]:
t6 = torch.tensor(data=[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=torch.float)
print(t6, t6.shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]]) torch.Size([2, 2, 3])


In [12]:
# (1 + 7) / 2 = 4
# (2 + 8) / 2 = 5
# (3 + 9) / 2 = 6
#
# (4 + 10) / 2 = 7
# (5 + 11) / 2 = 8
# (6 + 12) / 2 = 9
# Calculating the mean by traversing over the elements into the page (dimension 0).
t7 = t6.mean(dim=0, keepdim=True)
print(t7, t7.shape)

tensor([[[4., 5., 6.],
         [7., 8., 9.]]]) torch.Size([1, 2, 3])


In [13]:
# Calculates mean over each column in each 2D tensor (groups of tensors you obtain by 
# traversing in dimension 1).
#
# (1 + 4) / 2 = 2.5
# (2 + 5) / 2 = 3.5
# (3 + 6) / 2 = 4.5
#
# (7 + 10) / 2 = 8.5
# (8 + 11) / 2 = 9.5
# (9 + 12) / 2 = 10.5
t8 = t6.mean(dim=1, keepdim=True)
print(t8, t8.shape)

tensor([[[ 2.5000,  3.5000,  4.5000]],

        [[ 8.5000,  9.5000, 10.5000]]]) torch.Size([2, 1, 3])


In [14]:
# Calculates the mean over each row in each 1D tensor (tensors you obtain by traversion in dimension 2).
#
# (1 + 2 + 3) / 3 = 2
# (4 + 5 + 6) / 3 = 5
#
# (7 + 8 + 9) / 3 = 8
# (10 + 11 + 12) / 3 = 11
t9 = t6.mean(dim=2, keepdim=True)
print(t9, t9.shape)

tensor([[[ 2.],
         [ 5.]],

        [[ 8.],
         [11.]]]) torch.Size([2, 2, 1])


In [15]:
# Calculates the mean over all the elements in the tensor.
#
# sigma([1, 12]) / 12 = 6.5
t10 = t6.mean()
print(t10, t10.shape)

tensor(6.5000) torch.Size([])


In [16]:
t11 = torch.tensor(data=[[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]], dtype=torch.float)
print(t11, t11.shape)

tensor([[[[ 1.,  2.],
          [ 3.,  4.]],

         [[ 5.,  6.],
          [ 7.,  8.]]],


        [[[ 9., 10.],
          [11., 12.]],

         [[13., 14.],
          [15., 16.]]]]) torch.Size([2, 2, 2, 2])


In [17]:
# We get 3D tensors as we traverse in dimension 0. Starting with each element, traverse to the 
# corresponding element in the all the 3D tensors and calculate the mean of all these elements.
# Example would be to start from (1, 1, 1, 1) then go to (2, 1, 1, 1).
# t11[1][1][1][1] = 1, t11[2][1][1][1] = 9. We only have 2 3D tensors. So, the mean is (1 + 9) / 2 = 5
# t11[1][1][1][2] = 2, t11[2][1][1][2] = 10. So, the mean in this case is (2 + 10) / 2 = 6
#  
# (1 + 9) / 2 = 5
# (2 + 10) / 2 = 6
# (3 + 11) / 2 = 7
# (4 + 12) / 2 = 8
# (5 + 13) / 2 = 9
# (6 + 14) / 2 = 10
# (7 + 15) / 2 = 11
# (8 + 16) / 2 = 12
t12 = t11.mean(dim=0, keepdim=True)
print(t12, t12.shape)

tensor([[[[ 5.,  6.],
          [ 7.,  8.]],

         [[ 9., 10.],
          [11., 12.]]]]) torch.Size([1, 2, 2, 2])


In [18]:
# We get groups of 2D tensors as we traverse in dimension 1. 
# In each group of 2D tensors, we collapse the group to get a single 2D tensor.
#
# The groups of 2D tensors are:
# group1 --> [[1, 2], [3, 4]] and [[5, 6], [7, 8]]
# group2 --> [[9, 10], [11, 12]] and [[13, 14], [15, 16]]
#
# Collapse 2D tensors in group 1 into a single 2D tensor by calculating the mean. Similarly in group 2.
# 
# group 1 means:
# (1 + 5) / 2 = 3
# (2 + 6) / 2 = 4
# (3 + 7) / 2 = 5
# (4 + 8) / 2 = 6
#
# group 2 means:
# (9 + 13) / 2 = 11
# (10 + 14) / 2 = 12
# (11 + 15) / 2 = 13
# (12 + 16) / 2 = 14
t13 = t11.mean(dim=1, keepdim=True)
print(t13, t13.shape)

tensor([[[[ 3.,  4.],
          [ 5.,  6.]]],


        [[[11., 12.],
          [13., 14.]]]]) torch.Size([2, 1, 2, 2])


In [20]:
# We get groups of 1D tensors as we traverse in dimension 2.
# In each group of 1D tensors, we collapse the group to get a single 1D tensor.
#
# The groups of 1D tensors are:
# group1 --> [1, 2] and [3, 4]
# group2 --> [5, 6] and [7, 8]
# group3 --> [9, 10] and [11, 12]
# group4 --> [13, 14] and [15, 16]
#
# Collapse 1D tensors in each group into a single 1D tensor by calculating the means.
#
# group 1 means:
# (1 + 3) / 2 = 2
# (2 + 4) / 2 = 3
#
# group2 means:
# (5 + 7) / 2 = 6
# (6 + 8) / 2 = 7
#
# group3 means:
# (9 + 11) / 2 = 10
# (10 + 12) / 2 = 11
# 
# group4 means:
# (13 + 15) / 2 = 14
# (14 + 16) / 2 = 15 
t14 = t11.mean(dim=2, keepdim=True)
print(t14, t14.shape)

tensor([[[[ 2.,  3.]],

         [[ 6.,  7.]]],


        [[[10., 11.]],

         [[14., 15.]]]]) torch.Size([2, 2, 1, 2])


In [22]:
# We get groups of individual numbers as we traverse in dimension 3.
# In each group of numbers, we collapse the numbers to get a single number (mean of the numbers in the group).
#
# The groups of numbers are:
# group1 --> 1, 2
# group2 --> 3, 4
# group3 --> 5, 6
# group4 --> 7, 8
# group5 --> 9, 10
# group6 --> 11, 12
# group7 --> 13, 14
# group8 --> 15, 16
#
# group 1 mean:
# (1 + 2) / 2 = 1.5
# 
# group 2 mean:
# (3 + 4) / 2 = 3.5
#
# group 3 mean:
# (5 + 6) / 2 = 5.5
# 
# group 4 mean:
# (7 + 8) / 2 = 7.5
#
# group 5 mean:
# (9 + 10) / 2 = 9.5
# 
# group 6 mean:
# (11 + 12) / 2 = 11.5
#
# group 7 mean:
# (13 + 14) / 2 = 13.5
# 
# group 8 mean:
# (15 + 16) / 2 = 15.5
t15 = t11.mean(dim=3, keepdim=True)
print(t15, t15.shape)

tensor([[[[ 1.5000],
          [ 3.5000]],

         [[ 5.5000],
          [ 7.5000]]],


        [[[ 9.5000],
          [11.5000]],

         [[13.5000],
          [15.5000]]]]) torch.Size([2, 2, 2, 1])


## [torch.topk](https://pytorch.org/docs/stable/generated/torch.topk.html#torch.topk)

In [7]:
# Creating a random tensor to demonstrate the topk() function.
t16 = torch.randn(size=(10, 10))
print(f"shape of t16: {t16.shape}")
print(f"t16: {t16}")

shape of t16: torch.Size([10, 10])
t16: tensor([[ 0.4233,  0.8199,  0.5050, -1.0926, -0.4212,  0.5178,  0.3874, -1.0537,
          0.8778, -0.6597],
        [ 0.7666,  1.0237,  1.1167, -1.2751, -0.3338, -0.3952, -0.9140, -1.2936,
         -0.0939,  0.7553],
        [ 0.6098,  1.6296, -0.7219, -0.4328, -0.6557, -0.2463, -0.8440,  1.3226,
         -1.8629,  0.9046],
        [-0.5263,  0.3437,  0.9476,  0.2662, -0.2333,  1.2251,  0.1595, -0.2546,
          0.6220,  0.7127],
        [-1.3790, -2.2478, -1.6606,  0.9969, -0.3939,  0.2530,  1.9350,  1.9100,
         -0.3107, -0.4832],
        [ 0.1390,  0.5505,  1.5105, -0.5408, -0.6709, -0.3560, -0.5769, -0.1849,
         -1.4690, -0.6870],
        [ 1.9623,  0.8789, -0.9080,  0.0173,  0.2558,  0.5635, -1.8750, -1.2360,
          0.2301, -0.4862],
        [ 0.4545, -0.1014,  2.1530,  0.8208, -1.5959, -0.3814, -1.1091, -0.9797,
         -0.1718, -0.2841],
        [-1.0450, -1.6378,  0.2858,  0.9467, -0.3922,  1.1334,  0.6068,  0.6772,
       

In [ ]:
# This returns the top k (3 values here) values and the corresponding indices in the tensors present along 
# the last dimension. For the 0th tensor i.e., t16[0]
# The 3 largest values and their corresponding indices are [(0.8778, 8), (0.8199, 1), (0.5178, 5)]
t17_top_values, t17_top_indices = t16.topk(k=3, dim=-1, largest=True)
print(f"shape of t17_top_values: {t17_top_values.shape}")
print(f"t17_top_values: {t17_top_values}")
print("-" * 150)
print(f"shape of t17_top_indices: {t17_top_indices.shape}")
print(f"t17_top_indices: {t17_top_indices}")
print("-" * 150)

shape of t17_top_values: torch.Size([10, 3])
t17_top_values: tensor([[0.8778, 0.8199, 0.5178],
        [1.1167, 1.0237, 0.7666],
        [1.6296, 1.3226, 0.9046],
        [1.2251, 0.9476, 0.7127],
        [1.9350, 1.9100, 0.9969],
        [1.5105, 0.5505, 0.1390],
        [1.9623, 0.8789, 0.5635],
        [2.1530, 0.8208, 0.4545],
        [1.1334, 0.9467, 0.7691],
        [1.6317, 1.1379, 0.4411]])
------------------------------------------------------------------------------------------------------------------------------------------------------
shape of t17_top_indices: torch.Size([10, 3])
t17_top_indices: tensor([[8, 1, 5],
        [2, 1, 0],
        [1, 7, 9],
        [5, 2, 9],
        [6, 7, 3],
        [2, 1, 0],
        [0, 1, 5],
        [2, 3, 0],
        [5, 3, 9],
        [4, 9, 1]])
------------------------------------------------------------------------------------------------------------------------------------------------------
