In [55]:
# In this notebook, you learn:
#
# 1) What does torch.unsqueeze do?
# 2) What does torch.nn.functional.pad do?
# 3) How to slice a tensor?
# 4) What does torch.unbind do?

In [3]:
import torch

## [torch.unsqueeze](https://www.google.com/url?q=https%3A%2F%2Fpytorch.org%2Fdocs%2Fstable%2Fgenerated%2Ftorch.unsqueeze.html)

In [2]:
# unsqueeze basically adds a dimension at the given position. Lets think of a tensor as a container of 
# smaller tensors. If dim = 2 is used with unsqueeze, it means we go inside 2 containers and add a 
# container for all the tensors after traversing 2 steps i.e., we traverse 0, 1 dimensions and add an 
# extra dimension to every tensor we encounter after traversing 0, 1 dimensions.    

In [3]:
t1 = torch.tensor(data=[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print("shape: ", t1.shape)
print("t1: ", t1)

shape:  torch.Size([2, 3, 3])
t1:  tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])


In [6]:
# Creates a new dimension (which acts as dimension 0) and places the original tensor 't1' along this dimension.
# To summarize, it just adds an additional container on top of our tensor 't1' to create 't2'.
t2 = torch.unsqueeze(input=t1, dim = 0)
print("shape: ", t2.shape)
print("t2: ", t2)

shape:  torch.Size([1, 2, 3, 3])
t2:  tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]])


In [7]:
# Traverse 1 level inside (1 container) 't1'. We get the 2 '2D' tensors [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and 
# [[10, 11, 12], [13, 14, 15], [16, 17, 18]]. Each of these two tensors of shape (3, 3) are put inside another 
# container to create new tensors of shape (1, 3, 3). So, finally we get a '4D' tensor containing 2 '3D' tensors. 
t3 = torch.unsqueeze(input=t1, dim=1)
print("shape: ", t3.shape)
print("t3: ", t3)

shape:  torch.Size([2, 1, 3, 3])
t3:  tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]]],


        [[[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]])


In [8]:
# Traverse 2 levels inside (1 container) 't1'. We get the six '1D' tensors [1, 2, 3], [4, 5, 6], [7, 8, 9] and 
# [10, 11, 12], [13, 14, 15], [16, 17, 18]. Each of these six tensors of shape (3,) are put inside another 
# container to create new tensors of shape (1, 3). So, finally we get a '4D' tensor containing 2 '3D' tensors. 
t4 = torch.unsqueeze(input=t1, dim=2)
print("shape: ", t4.shape)
print("t4: ", t4)

shape:  torch.Size([2, 3, 1, 3])
t4:  tensor([[[[ 1,  2,  3]],

         [[ 4,  5,  6]],

         [[ 7,  8,  9]]],


        [[[10, 11, 12]],

         [[13, 14, 15]],

         [[16, 17, 18]]]])


In [16]:
# Traverse 3 levels inside (1 container) 't1'. We get the 18 individual numbers 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 
# 11, 12, 13, 14, 15, 16, 17, 18. Each of these 18 numbers are put inside a container to create new tensors of shape (1,). 
t5 = torch.unsqueeze(input=t1, dim=3)
print(t5, t5.shape)

tensor([[[[ 1],
          [ 2],
          [ 3]],

         [[ 4],
          [ 5],
          [ 6]],

         [[ 7],
          [ 8],
          [ 9]]],


        [[[10],
          [11],
          [12]],

         [[13],
          [14],
          [15]],

         [[16],
          [17],
          [18]]]]) torch.Size([2, 3, 3, 1])


## [torch.squeeze](https://pytorch.org/docs/main/generated/torch.squeeze.html#torch-squeeze)

In [ ]:
# TO BE ADDED

## [torch.nn.functional.pad](https://pytorch.org/docs/stable/generated/torch.nn.functional.pad.html#torch.nn.functional.pad)

In [ ]:
# Pads the given 'input' tensor with the provided 'value'.
# argument pad=(3, 2) means pads 3 values at the start and 2 values at the end for the tensors in the last dimension.
# So, [10, 20] tensor when padded using pad=(3, 2) turns into [2.5, 2.5, 2.5, 10.0, 20.0, 2.5, 2.5].
# Size in the last dimension increase by 3 + 2 = 5.
#
# In general, then pad has the following form:
#
# (padding_left, padding_right) to pad only the last dimension of the input tensor. 
# (padding_left, padding_right, padding_top, padding_bottom) to pad the last 2 dimensions of the input tensor.
# (padding_left, padding_right, padding_top, padding_bottom, padding_front, padding_back) to pad the last 3 
#       dimensions of the input tensor.
# 
# Similary extend the logic to all higher dimensions.
#

In [7]:
t6 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]], dtype=float)
print(t6, t6.shape)


tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[13., 14., 15.],
         [16., 17., 18.]]], dtype=torch.float64) torch.Size([3, 2, 3])


In [6]:
# Notice that it added 3 values at the start and 2 values at the end for the tensors in the last dimension.
t7 = torch.nn.functional.pad(input=t6, pad=(3, 2), mode="constant", value=2.5)
print(t7, t7.shape)

tensor([[[ 2.5000,  2.5000,  2.5000,  1.0000,  2.0000,  3.0000,  2.5000,
           2.5000],
         [ 2.5000,  2.5000,  2.5000,  4.0000,  5.0000,  6.0000,  2.5000,
           2.5000]],

        [[ 2.5000,  2.5000,  2.5000,  7.0000,  8.0000,  9.0000,  2.5000,
           2.5000],
         [ 2.5000,  2.5000,  2.5000, 10.0000, 11.0000, 12.0000,  2.5000,
           2.5000]],

        [[ 2.5000,  2.5000,  2.5000, 13.0000, 14.0000, 15.0000,  2.5000,
           2.5000],
         [ 2.5000,  2.5000,  2.5000, 16.0000, 17.0000, 18.0000,  2.5000,
           2.5000]]], dtype=torch.float64) torch.Size([3, 2, 8])


In [8]:
# Notice that it added two new 1D tensors for every 2D tensor. 
t8 = torch.nn.functional.pad(input=t6, pad=(3, 2, 1, 1), mode="constant", value=2.5)
print(t8, t8.shape)

tensor([[[ 2.5000,  2.5000,  2.5000,  2.5000,  2.5000,  2.5000,  2.5000,
           2.5000],
         [ 2.5000,  2.5000,  2.5000,  1.0000,  2.0000,  3.0000,  2.5000,
           2.5000],
         [ 2.5000,  2.5000,  2.5000,  4.0000,  5.0000,  6.0000,  2.5000,
           2.5000],
         [ 2.5000,  2.5000,  2.5000,  2.5000,  2.5000,  2.5000,  2.5000,
           2.5000]],

        [[ 2.5000,  2.5000,  2.5000,  2.5000,  2.5000,  2.5000,  2.5000,
           2.5000],
         [ 2.5000,  2.5000,  2.5000,  7.0000,  8.0000,  9.0000,  2.5000,
           2.5000],
         [ 2.5000,  2.5000,  2.5000, 10.0000, 11.0000, 12.0000,  2.5000,
           2.5000],
         [ 2.5000,  2.5000,  2.5000,  2.5000,  2.5000,  2.5000,  2.5000,
           2.5000]],

        [[ 2.5000,  2.5000,  2.5000,  2.5000,  2.5000,  2.5000,  2.5000,
           2.5000],
         [ 2.5000,  2.5000,  2.5000, 13.0000, 14.0000, 15.0000,  2.5000,
           2.5000],
         [ 2.5000,  2.5000,  2.5000, 16.0000, 17.0000, 18.0000,  2

## Slicing in PyTorch

In [42]:
# Lets start with a simple 2D tensor and then move to higher dimensions.
t9 = torch.arange(start=1, end=21).reshape(4, 5)
print(t9.shape)
t9

torch.Size([4, 5])


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [43]:
# Slicing is basically indexing into the tensor to retrieve parts of the tensor. This is similar to indexing in arrays.
# The tensor 't9' has 2 dimensions and so we can use 2 pairs of start-end tuples to retrieve the slices.

In [44]:
# dimension 0 --> : --> This means start=0 and end=4.
#                       This retrieves all the 4 tensors along dimension 0 i.e., all 4 rows.
# dimension 1 --> 1:4 --> This means start=1 and end=4
#                         From each of the 4 tensors obtained after 0th step, this retrives the elements between indices
#                         1 and 3 (inclusive).
t10 = t9[:, 1:4]
print(t10.shape)
print(t10)

torch.Size([4, 3])
tensor([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]])


In [45]:
# dimension 0 --> 0 --> This means just get the 0th sub-tensor along dimension 0. Since we specified only 1 number, this
#                       will be removed and the resultant tensor will have 1 less dimension.
# dimension 1 --> 1:4 --> This again means start=1 and end=4.
#                         We only have 1 tensor obtained from 0th step. So, this just retrieves all the elements between
#                         indices 1 and 3 (inclusive) from the tensor obtained in 0th step.
t11 = t9[0, 1:4]
print(t11.shape)
t11

torch.Size([3])


tensor([2, 3, 4])

In [46]:
# dimension 0 --> : --> This means start=0 and end=4.
#                       This retrieves all the 4 tensors along dimension 0 i.e., all 4 rows.
# dimension 1 --> 2:2 --> This means retrieve no elements along this dimension. This will result in an empty tensor.
#
# Even though we get an empty tensor, the shape is still preserved.
t12 = t9[:, 2:2]
print(t12.shape)
print(t12)

torch.Size([4, 0])
tensor([], size=(4, 0), dtype=torch.int64)


In [47]:
# dimension 0 --> 0:3 --> This means start=0 and end=3. This will retrieve all the sub-tensors between indices 0 and 
#                         2 (inclusive).
# dimension 1 --> 2:5 --> This means start=2 and end=5.
#                         From each of the tensors retrieved in step 0, it retrieves the elements between indices 2
#                         4 (inclusive).
t13 = t9[0:3, 2:5]
print(t13.shape)
t13

torch.Size([3, 3])


tensor([[ 3,  4,  5],
        [ 8,  9, 10],
        [13, 14, 15]])

In [48]:
# Now, let's just try the same on a 4D tensor.

In [52]:
t14 = torch.arange(start=1, end=82).reshape(3, 3, 3, 3)
print(t14.shape)
t14

torch.Size([3, 3, 3, 3])


tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]],


        [[[28, 29, 30],
          [31, 32, 33],
          [34, 35, 36]],

         [[37, 38, 39],
          [40, 41, 42],
          [43, 44, 45]],

         [[46, 47, 48],
          [49, 50, 51],
          [52, 53, 54]]],


        [[[55, 56, 57],
          [58, 59, 60],
          [61, 62, 63]],

         [[64, 65, 66],
          [67, 68, 69],
          [70, 71, 72]],

         [[73, 74, 75],
          [76, 77, 78],
          [79, 80, 81]]]])

In [50]:
# The tensor 't14' has 4 dimensions and so we can use 4 pairs of start-end tuples to retrieve the slices.

In [53]:
# Let's evaluate the slicing from left to right.
# 0:2 --> Retrieves '2' 3D sub-tensors along dimension 0.
#
# 0:2 --> Retrieves '2' 2D sub-tensors from each of the two 3D sub-tensors retrieved in step 0.
#
# 1:2 --> Retrieves '1' 1D sub-tensor from each of the four 2D sub-tensor obtained after step 1.
#
# 2   --> Retrieves just the 2nd element in each of the '4' 1D sub-tensors obtained after step 2.
t15 = t14[0:2, 0:2, 1:2, 2]
print(t15.shape)
t15

torch.Size([2, 2, 1])


tensor([[[ 6],
         [15]],

        [[33],
         [42]]])

In [54]:
# You can keep using the same logic no matter what the dimension of the initial tensor is.

## [torch.unbind](https://pytorch.org/docs/stable/generated/torch.unbind.html)

In [1]:
# Honestly, the explanation on the Pytorch website doesn't make any sense. However, apprently 'unbind' is a
# specific way of slicing into the tensor. So, it would be helpful if you understood how slicing works from
# the above function.
#
# 'unbind' is the same as applying 'slicing' multiple times along the specified dimension. It is easier to
# understand from the runs below instead of trying to explain it.

In [56]:
t16 = torch.arange(start=1, end=61).reshape(3, 4, 5)
print(t16.shape)
t16

torch.Size([3, 4, 5])


tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40]],

        [[41, 42, 43, 44, 45],
         [46, 47, 48, 49, 50],
         [51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60]]])

In [57]:
print(t16[0, :, :])
print(t16[1, :, :])
print(t16[2, :, :])

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
tensor([[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]])
tensor([[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]])


In [59]:
l1 = torch.unbind(input=t16, dim=0)
print(len(l1))
l1

3


(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]),
 tensor([[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40]]),
 tensor([[41, 42, 43, 44, 45],
         [46, 47, 48, 49, 50],
         [51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60]]))

In [61]:
print(t16[:, 0, :])
print(t16[:, 1, :])
print(t16[:, 2, :])
print(t16[:, 3, :])

tensor([[ 1,  2,  3,  4,  5],
        [21, 22, 23, 24, 25],
        [41, 42, 43, 44, 45]])
tensor([[ 6,  7,  8,  9, 10],
        [26, 27, 28, 29, 30],
        [46, 47, 48, 49, 50]])
tensor([[11, 12, 13, 14, 15],
        [31, 32, 33, 34, 35],
        [51, 52, 53, 54, 55]])
tensor([[16, 17, 18, 19, 20],
        [36, 37, 38, 39, 40],
        [56, 57, 58, 59, 60]])


In [63]:
l2 = torch.unbind(input=t16, dim=1)
print(len(l2))
l2

4


(tensor([[ 1,  2,  3,  4,  5],
         [21, 22, 23, 24, 25],
         [41, 42, 43, 44, 45]]),
 tensor([[ 6,  7,  8,  9, 10],
         [26, 27, 28, 29, 30],
         [46, 47, 48, 49, 50]]),
 tensor([[11, 12, 13, 14, 15],
         [31, 32, 33, 34, 35],
         [51, 52, 53, 54, 55]]),
 tensor([[16, 17, 18, 19, 20],
         [36, 37, 38, 39, 40],
         [56, 57, 58, 59, 60]]))

In [64]:
print(t16[:, :, 0])
print(t16[:, :, 1])
print(t16[:, :, 2])
print(t16[:, :, 3])
print(t16[:, :, 4])

tensor([[ 1,  6, 11, 16],
        [21, 26, 31, 36],
        [41, 46, 51, 56]])
tensor([[ 2,  7, 12, 17],
        [22, 27, 32, 37],
        [42, 47, 52, 57]])
tensor([[ 3,  8, 13, 18],
        [23, 28, 33, 38],
        [43, 48, 53, 58]])
tensor([[ 4,  9, 14, 19],
        [24, 29, 34, 39],
        [44, 49, 54, 59]])
tensor([[ 5, 10, 15, 20],
        [25, 30, 35, 40],
        [45, 50, 55, 60]])


In [65]:
l3 = torch.unbind(input=t16, dim=2)
print(len(l3))
l3

5


(tensor([[ 1,  6, 11, 16],
         [21, 26, 31, 36],
         [41, 46, 51, 56]]),
 tensor([[ 2,  7, 12, 17],
         [22, 27, 32, 37],
         [42, 47, 52, 57]]),
 tensor([[ 3,  8, 13, 18],
         [23, 28, 33, 38],
         [43, 48, 53, 58]]),
 tensor([[ 4,  9, 14, 19],
         [24, 29, 34, 39],
         [44, 49, 54, 59]]),
 tensor([[ 5, 10, 15, 20],
         [25, 30, 35, 40],
         [45, 50, 55, 60]]))