In [2]:
# In this notebook, you learn:
# 
# 1) How torch.zeros works?
# 2) How torch.arange works?
# 3) How torch.exp works?
# 4) How torch.ones works?

In [3]:
import torch

## [torch.zeros](https://pytorch.org/docs/stable/generated/torch.zeros.html#torch-zeros)

In [5]:
# Simple function that just created a tensor of all zeros with the given shape.
t1 = torch.zeros(size=(2, 3, 4), dtype=torch.float)
print(t1)
print(t1.shape)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


## [torch.arange](https://pytorch.org/docs/stable/generated/torch.arange.html#torch-arange)

In [6]:
# Creates a 1D tensor that starts from 0 and runs until end (10) with step size of 1.
t2 = torch.arange(end=10)
print(t2)
print(t2.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])


In [8]:
# Creates a 1D tensor that starts from start (4) and runs until end (10) with step size of 1.
t3 = torch.arange(start=4, end=10)
print(t3)
print(t3.shape)

tensor([4, 5, 6, 7, 8, 9])
torch.Size([6])


In [9]:
# Creates a 1D tensor that start from start (4) and runs until end (13) with step size of 3.
t4 = torch.arange(start=4, end=13, step=3)
print(t4)
print(t4.shape)

tensor([ 4,  7, 10])
torch.Size([3])


## [torch.exp](https://pytorch.org/docs/stable/generated/torch.exp.html#torch-exp)

In [10]:
# Calculates the exponential (e^{tensor_element}) for every element in the tensor and returns the
# new tensor
t5 = torch.arange(12).reshape(2, 3, 2) 
print(t5)
print(t5.shape)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])
torch.Size([2, 3, 2])


In [11]:
t6 = torch.exp(input=t5)
print(t6)
print(t6.shape)

tensor([[[1.0000e+00, 2.7183e+00],
         [7.3891e+00, 2.0086e+01],
         [5.4598e+01, 1.4841e+02]],

        [[4.0343e+02, 1.0966e+03],
         [2.9810e+03, 8.1031e+03],
         [2.2026e+04, 5.9874e+04]]])
torch.Size([2, 3, 2])


## [torch.ones](https://pytorch.org/docs/stable/generated/torch.ones.html#torch-ones)

In [6]:
# Creates a tensor of all ones with the given shape.
t7 = torch.ones(size=(2, 3, 4), dtype=torch.int64)
print("shape: ", t7.shape)
print("t7: ", t7)

shape:  torch.Size([2, 3, 4])
t7:  tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])
